# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(551, 471))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(1.0)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: white;")
        self.sideBar = QtWidgets.QListWidget(Form)
        self.sideBar.setEnabled(True)
        self.sideBar.setGeometry(QtCore.QRect(0, 150, 141, 321))
        self.sideBar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sideBar.setAutoFillBackground(True)
        self.sideBar.setStyleSheet("QListWidget {\n"
"    show-decoration-selected: 1; /* make the selection span the entire width of the view */\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    margin : 10px;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: #EEEEEE;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: 1px solid #6a6ea9;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #ABAFE5, stop: 1 #8588B2);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6a6ea9, stop: 1 #888dd9);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #FAFBFE, stop: 1 #DCDEF1);\n"
"}")
        self.sideBar.setFrameShape(QtWidgets.QFrame.Box)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sideBar.setAutoScrollMargin(16)
        self.sideBar.setObjectName("sideBar")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/main_menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.sideBar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.sideBar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.sideBar.addItem(item)
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setEnabled(True)
        self.logo.setGeometry(QtCore.QRect(0, 30, 141, 121))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/Datas/icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.sideBarB = QtWidgets.QPushButton(Form)
        self.sideBarB.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.sideBarB.setStyleSheet("")
        self.sideBarB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/menu_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarB.setIcon(icon3)
        self.sideBarB.setIconSize(QtCore.QSize(50, 25))
        self.sideBarB.setAutoDefault(True)
        self.sideBarB.setDefault(False)
        self.sideBarB.setFlat(False)
        self.sideBarB.setObjectName("sideBarB")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(30, 0, 521, 31))
        self.title.setStatusTip("")
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAutoFillBackground(False)
        self.title.setFrameShape(QtWidgets.QFrame.Panel)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.main_menu = QtWidgets.QWidget(Form)
        self.main_menu.setGeometry(QtCore.QRect(0, 30, 551, 441))
        self.main_menu.setObjectName("main_menu")
        self.fanB = QtWidgets.QPushButton(self.main_menu)
        self.fanB.setGeometry(QtCore.QRect(290, 120, 121, 91))
        self.fanB.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fanB.setIcon(icon4)
        self.fanB.setIconSize(QtCore.QSize(80, 80))
        self.fanB.setFlat(True)
        self.fanB.setObjectName("fanB")
        self.doorB = QtWidgets.QPushButton(self.main_menu)
        self.doorB.setGeometry(QtCore.QRect(200, 230, 121, 91))
        self.doorB.setText("")
        self.doorB.setIcon(icon4)
        self.doorB.setIconSize(QtCore.QSize(80, 80))
        self.doorB.setFlat(True)
        self.doorB.setObjectName("doorB")
        self.lampB = QtWidgets.QPushButton(self.main_menu)
        self.lampB.setGeometry(QtCore.QRect(120, 120, 121, 91))
        self.lampB.setText("")
        self.lampB.setIcon(icon4)
        self.lampB.setIconSize(QtCore.QSize(80, 80))
        self.lampB.setFlat(True)
        self.lampB.setObjectName("lampB")
        self.moistureL = QtWidgets.QLabel(self.main_menu)
        self.moistureL.setGeometry(QtCore.QRect(110, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.moistureL.setFont(font)
        self.moistureL.setAlignment(QtCore.Qt.AlignCenter)
        self.moistureL.setObjectName("moistureL")
        self.temperatureL = QtWidgets.QLabel(self.main_menu)
        self.temperatureL.setGeometry(QtCore.QRect(290, 60, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.temperatureL.setFont(font)
        self.temperatureL.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureL.setObjectName("temperatureL")
        self.statusL = QtWidgets.QLabel(self.main_menu)
        self.statusL.setGeometry(QtCore.QRect(170, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.statusL.setFont(font)
        self.statusL.setAlignment(QtCore.Qt.AlignCenter)
        self.statusL.setObjectName("statusL")
        self.assistant = QtWidgets.QWidget(Form)
        self.assistant.setGeometry(QtCore.QRect(0, 30, 551, 441))
        self.assistant.setObjectName("assistant")
        self.textEdit = QtWidgets.QTextEdit(self.assistant)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 551, 391))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit.setReadOnly(True)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.msg = QtWidgets.QLineEdit(self.assistant)
        self.msg.setEnabled(True)
        self.msg.setGeometry(QtCore.QRect(0, 390, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.msg.setFont(font)
        self.msg.setAutoFillBackground(False)
        self.msg.setFrame(True)
        self.msg.setCursorPosition(0)
        self.msg.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.msg.setObjectName("msg")
        self.music_player = QtWidgets.QWidget(Form)
        self.music_player.setGeometry(QtCore.QRect(0, 30, 551, 441))
        self.music_player.setObjectName("music_player")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.music_player)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 531, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.sliderL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.sliderL.setContentsMargins(0, 0, 0, 0)
        self.sliderL.setObjectName("sliderL")
        self.time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.sliderL.addWidget(self.time)
        self.slider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.slider.setMaximum(100)
        self.slider.setProperty("value", 0)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.sliderL.addWidget(self.slider)
        self.eta = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.eta.setFont(font)
        self.eta.setObjectName("eta")
        self.sliderL.addWidget(self.eta)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.music_player)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 531, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.controler = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.controler.setContentsMargins(0, 0, 0, 0)
        self.controler.setObjectName("controler")
        self.playB = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.playB.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playB.setIcon(icon5)
        self.playB.setIconSize(QtCore.QSize(60, 70))
        self.playB.setFlat(True)
        self.playB.setObjectName("playB")
        self.controler.addWidget(self.playB)
        self.pauseB = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pauseB.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseB.setIcon(icon6)
        self.pauseB.setIconSize(QtCore.QSize(60, 70))
        self.pauseB.setFlat(True)
        self.pauseB.setObjectName("pauseB")
        self.controler.addWidget(self.pauseB)
        self.stopB = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.stopB.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopB.setIcon(icon7)
        self.stopB.setIconSize(QtCore.QSize(60, 70))
        self.stopB.setFlat(True)
        self.stopB.setObjectName("stopB")
        self.controler.addWidget(self.stopB)
        self.v_UP = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.v_UP.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/v_UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.v_UP.setIcon(icon8)
        self.v_UP.setIconSize(QtCore.QSize(60, 70))
        self.v_UP.setFlat(True)
        self.v_UP.setObjectName("v_UP")
        self.controler.addWidget(self.v_UP)
        self.v_DOWN = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.v_DOWN.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/v_DOWN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.v_DOWN.setIcon(icon9)
        self.v_DOWN.setIconSize(QtCore.QSize(60, 70))
        self.v_DOWN.setFlat(True)
        self.v_DOWN.setObjectName("v_DOWN")
        self.controler.addWidget(self.v_DOWN)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.music_player)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 280, 531, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.controler_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.controler_2.setContentsMargins(0, 0, 0, 0)
        self.controler_2.setObjectName("controler_2")
        self.prevSB = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.prevSB.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevSB.setIcon(icon10)
        self.prevSB.setIconSize(QtCore.QSize(60, 60))
        self.prevSB.setFlat(True)
        self.prevSB.setObjectName("prevSB")
        self.controler_2.addWidget(self.prevSB)
        self.nextSB = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.nextSB.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/Datas/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextSB.setIcon(icon11)
        self.nextSB.setIconSize(QtCore.QSize(60, 60))
        self.nextSB.setFlat(True)
        self.nextSB.setObjectName("nextSB")
        self.controler_2.addWidget(self.nextSB)
        self.soundN = QtWidgets.QLabel(self.music_player)
        self.soundN.setGeometry(QtCore.QRect(10, 30, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.soundN.setFont(font)
        self.soundN.setText("")
        self.soundN.setAlignment(QtCore.Qt.AlignCenter)
        self.soundN.setObjectName("soundN")
        self.vBar = QtWidgets.QProgressBar(self.music_player)
        self.vBar.setGeometry(QtCore.QRect(489, 20, 31, 181))
        self.vBar.setStyleSheet("QProgressBar{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: blue;\n"
"    margin: 1px;\n"
"    border-radius: 3px\n"
"}")
        self.vBar.setProperty("value", 0)
        self.vBar.setOrientation(QtCore.Qt.Vertical)
        self.vBar.setObjectName("vBar")
        self.assistant.raise_()
        self.music_player.raise_()
        self.main_menu.raise_()
        self.logo.raise_()
        self.sideBar.raise_()
        self.title.raise_()
        self.sideBarB.raise_()
        self.logo.setBuddy(self.logo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Reji Asistan"))
        self.sideBar.setSortingEnabled(False)
        __sortingEnabled = self.sideBar.isSortingEnabled()
        self.sideBar.setSortingEnabled(False)
        item = self.sideBar.item(0)
        item.setText(_translate("Form", "Ana Menü"))
        item = self.sideBar.item(1)
        item.setText(_translate("Form", "Asistan"))
        item = self.sideBar.item(2)
        item.setText(_translate("Form", "Müzik Oynatıcı"))
        self.sideBar.setSortingEnabled(__sortingEnabled)
        self.title.setText(_translate("Form", "Ana Menü"))
        self.moistureL.setText(_translate("Form", "Nem: %100"))
        self.temperatureL.setText(_translate("Form", "Sıcaklık: 300C"))
        self.statusL.setText(_translate("Form", "Durum: Kapalı"))
        self.time.setText(_translate("Form", "0.00"))
        self.eta.setText(_translate("Form", "0.00"))

from Modules import gui_rc
